name: Upload snapshot to staging

on:
  pull_request:
    branches:
      - staging
    types: [closed]
    paths:
      - "directus/snapshot/*"

jobs:
  Deploy:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged
    container:
      image: node:16
    steps:
      - name: Deploying code
        run: echo "Upload snapshot to staging"
