kind: pipeline
type: docker
name: Pipeline-test-create-react-app

steps:
  - name: restore cache
    image: drillster/drone-volume-cache
    settings:
      restore: true
      mount:
        - ./node_modules
    volumes:
      - name: cache
        path: /cache
    depends_on:
      - clone

  - name: install
    image: node:16
    commands:
      - npm ci --silent
    depends_on:
      - restore cache

  - name: tests
    image: node:16
    commands:
      - npm test
    depends_on:
      - install

  - name: build
    image: node:16
    commands:
      - npm run build
    depends_on:
      - tests

  - name: publish dev
    image: plugins/docker
    environment:
      NODE_ENV: development
    settings:
      registry: rg.fr-par.scw.cloud/agence-public
      repo: rg.fr-par.scw.cloud/agence-public/create-react-app_test
      tags: [ latest ]
      username:
        from_secret: DOCKER_REGISTRY_USERNAME
      password:
        from_secret: DOCKER_REGISTRY_PASS
    depends_on:
      - build

  - name: publish prod
    image: plugins/docker
    environment:
      NODE_ENV: production
    settings:
      registry: rg.fr-par.scw.cloud/agence-public
      repo: rg.fr-par.scw.cloud/agence-public/create-react-app_prod
      tags: [ latest ]
      username:
        from_secret: DOCKER_REGISTRY_USERNAME
      password:
        from_secret: DOCKER_REGISTRY_PASS
    depends_on:
      - build

  - name: ssh tests
    image: appleboy/drone-ssh
    settings:
      host: slatsh.com
      username: root
      key:
        from_secret: SSH_KEY
      passphrase: 
        from_secret: SSH_KEY_PASS
      port: 22
      script:
        - mkdir /root/test
    depends_on:
      - publish dev
      - publish prod

  - name: send telegram
    image: appleboy/drone-telegram
    settings:
      token: 
        from_secret: TELEGRAM_BOT_TOKEN
      to: 
        from_secret: TELEGRAM_BOT_CANAL
      message: >
        {{#success build.status}}
          build {{build.number}} succeeded. Good job.
        {{else}}
          build {{build.number}} failed. Fix me please.
        {{/success}}    

  - name: rebuild cache
    image: drillster/drone-volume-cache
    settings:
      rebuild: true
      mount:
        - ./node_modules
    volumes:
      - name: cache
        path: /cache
    depends_on:
      - send telegram

volumes:
  - name: cache
    host:
      path: /tmp/drone/cache