kind: pipeline
type: docker
name: Pipeline-test

steps:
  - name: Frontend
    image: node
    commands:
      - npm ci
      - npm test
      - npm start

  - name: Deploy Staging
    image: node
    environment:
      NODE_ENV: staging
    commands:
      - npm ci
      - npm test
      - npm start
    when:
      event:
      - promote
      target:
      - staging
  
  - name: Deploy Production
    image: node
    environment:
      NODE_ENV: production
    commands:
      - npm ci
      - npm test
      - npm start
    when:
      event:
      - promote
      target:
      - production