kind: pipeline
type: docker
name: Build

steps:
  # - name: restore cache
  #   image: drillster/drone-volume-cache
  #   settings:
  #     restore: true
  #     mount:
  #       - ./node_modules
  #   volumes:
  #     - name: cache
  #       path: /cache
  #   depends_on:
  #     - clone

  - name: install
    image: node:16
    volumes:
    - name: cache
      path: /drone/src/node_modules
    commands:
      - npm ci
    depends_on:
      - clone

  # - name: rebuild cache
  #   image: drillster/drone-volume-cache
  #   settings:
  #     rebuild: true
  #     mount:
  #       - ./node_modules
  #   volumes:
  #     - name: cache
  #       path: /cache
  #   depends_on:
  #     - install

  - name: tests
    image: node:16
    volumes:
    - name: cache
      path: /drone/src/node_modules
    commands:
      - npm test
    depends_on:
      - install

  - name: build
    image: node:16
    volumes:
      - name: cache
        path: /drone/src/node_modules
      - name: build
        path: /drone/src/
    commands:
      - npm run build
      - ls
      - pwd
    depends_on:
      - tests

  # - name: caching build
  #   image: drillster/drone-volume-cache
  #   settings:
  #     rebuild: true
  #     mount:
  #       - ./build
  #       - ./Dockerfile
  #   volumes:
  #     - name: build
  #       path: /build
  #   depends_on:
  #     - build

volumes:
  - name: cache
    host:
      path: /tmp/drone/node_modules
  - name: build
    host:
      path: /tmp/drone/build

---
kind: pipeline
type: docker
name: Publish

clone:
  disable: true

steps:
  # - name: restore build
  #   image: drillster/drone-volume-cache
  #   settings:
  #     restore: true
  #     mount:
  #       - ./build
  #       - ./Dockerfile
  #   volumes:
  #     - name: build
  #       path: /build

  - name: build
    image: node:16
    volumes:
      - name: build
        path: /drone/src/build
    commands:
      - ls

  - name: publish dev
    image: plugins/docker
    volumes:
      - name: build
        path: /drone/src/build
    environment:
      NODE_ENV: development
    settings:
      registry: rg.fr-par.scw.cloud/agence-public
      repo: rg.fr-par.scw.cloud/agence-public/create-react-app_test
      tags: [ latest ]
      cache_from: "rg.fr-par.scw.cloud/agence-public/create-react-app_test:latest"
      username:
        from_secret: DOCKER_REGISTRY_USERNAME
      password:
        from_secret: DOCKER_REGISTRY_PASS
    depends_on:
      - build

  - name: publish prod
    image: plugins/docker
    volumes:
      - name: build
        path: /drone/src/build
      - name: build
        path: /drone/src/build/Dockerfile
    environment:
      NODE_ENV: production
    settings:
      registry: rg.fr-par.scw.cloud/agence-public
      repo: rg.fr-par.scw.cloud/agence-public/create-react-app_prod
      tags: [ latest ]
      cache_from: "rg.fr-par.scw.cloud/agence-public/create-react-app_prod:latest"
      username:
        from_secret: DOCKER_REGISTRY_USERNAME
      password:
        from_secret: DOCKER_REGISTRY_PASS
    depends_on:
      - build

depends_on:
- Build

volumes:
  - name: build
    host:
      path: /tmp/drone/build

---
kind: pipeline
type: docker
name: Notify

clone:
  disable: true

steps:
  - name: send telegram
    image: appleboy/drone-telegram
    settings:
      token: 
        from_secret: TELEGRAM_BOT_TOKEN
      to: 
        from_secret: TELEGRAM_BOT_CANAL
      message: >
        {{#success build.status}}✅{{else}}❌{{/success}} Build {{build.status}}: *{{repo.fullname}}*
        build: {{build.number}}
        commit: {{build.branch}}:{{build.commit}}
        By: {{build.author}}
        {{build.message}}
        {{build.link}}

depends_on:
- Publish

trigger:
  status:
  - success
  - failure