kind: pipeline
type: docker
name: Pipeline-test-create-react-app

steps:
  - name: install
    image: node:16
    commands:
      - npm config set cache .npm-cache
      - npm ci --silent
      - npm install react-scripts@3.4.1 -g --silent

  - name: tests
    image: node:16
    commands:
      - npm test

  - name: build
    image: node:16
    commands:
      - npm run build

  - name: publish dev
    image: plugins/docker
    environment:
      NODE_ENV: development
    settings:
      registry: rg.fr-par.scw.cloud/agence-public
      repo: rg.fr-par.scw.cloud/agence-public/create-react-app_test
      tags: [ latest ]
      username:
        from_secret: DOCKER_REGISTRY_USERNAME
      password:
        from_secret: DOCKER_REGISTRY_PASS

  - name: publish prod
    image: plugins/docker
    environment:
      NODE_ENV: production
    settings:
      registry: rg.fr-par.scw.cloud/agence-public
      repo: rg.fr-par.scw.cloud/agence-public/create-react-app_prod
      tags: [ latest ]
      username:
        from_secret: DOCKER_REGISTRY_USERNAME
      password:
        from_secret: DOCKER_REGISTRY_PASS

  - name: send telegram notification
    image: appleboy/drone-telegram
    settings:
      token: 5253152176:AAFg7dxYouyt5Coj5e43J2LNLfwtIZCeLZw
      to: shankiflang
      message: >
        {{#success build.status}}
          build {{build.number}} succeeded. Good job.
        {{else}}
          build {{build.number}} failed. Fix me please.
        {{/success}}
    depends_on:
      - publish dev
      - publish prod