kind: pipeline
type: docker
name: Build

steps:
  - name: install
    image: node:16
    volumes:
    - name: cache
      path: /drone/src/node_modules
    commands:
      - npm ci
    depends_on:
      - clone
  - name: tests
    image: node:16
    volumes:
    - name: cache
      path: /drone/src/node_modules
    commands:
      - npm test
    depends_on:
      - install

  - name: build
    image: node:16
    volumes:
      - name: cache
        path: /drone/src/node_modules
    commands:
      - npm run build
    depends_on:
      - tests

  - name: publish image dev
    image: plugins/docker
    settings:
      registry: rg.fr-par.scw.cloud/agence-public
      repo: rg.fr-par.scw.cloud/agence-public/create-react-app_test
      tags: [ latest ]
      username:
        from_secret: DOCKER_REGISTRY_USERNAME
      password:
        from_secret: DOCKER_REGISTRY_PASS
    depends_on:
      - build
    when:
      branch:
        - develop

  - name: publish image staging
    image: plugins/docker
    settings:
      registry: rg.fr-par.scw.cloud/agence-public
      repo: rg.fr-par.scw.cloud/agence-public/create-react-app_staging
      tags: [ latest ]
      username:
        from_secret: DOCKER_REGISTRY_USERNAME
      password:
        from_secret: DOCKER_REGISTRY_PASS
    depends_on:
      - build
    when:
      branch:
        - staging

  - name: publish image prod
    image: plugins/docker
    settings:
      registry: rg.fr-par.scw.cloud/agence-public
      repo: rg.fr-par.scw.cloud/agence-public/create-react-app_prod
      tags: [ latest ]
      username:
        from_secret: DOCKER_REGISTRY_USERNAME
      password:
        from_secret: DOCKER_REGISTRY_PASS
    depends_on:
      - build
    when:
      branch:
        - master

trigger:
  branch:
  - develop
  - staging
  - master

volumes:
  - name: cache
    host:
      path: /tmp/drone/node_modules

---
# kind: pipeline
# type: docker
# name: Deploy to production

# steps:
#   - name: publish dev
#     image: plugins/docker
#     environment: 
#       NODE_TEXT: COUCOU C MWA
#     settings:
#       registry: rg.fr-par.scw.cloud/agence-public
#       repo: rg.fr-par.scw.cloud/agence-public/create-react-app_test
#       tags: [ latest ]
#       username:
#         from_secret: DOCKER_REGISTRY_USERNAME
#       password:
#         from_secret: DOCKER_REGISTRY_PASS

# trigger:
#   event:
#   - promote
#   target:
#   - develop

# volumes:
#   - name: cache
#     host:
#       path: /tmp/drone/node_modules
# ---
kind: pipeline
type: docker
name: Notify

clone:
  disable: true

steps:
  - name: send telegram
    image: appleboy/drone-telegram
    settings:
      token: 
        from_secret: TELEGRAM_BOT_TOKEN
      to: 
        from_secret: TELEGRAM_BOT_CANAL
      message: >
        {{#success build.status}}✅{{else}}❌{{/success}} Build {{build.status}}: *{{repo.fullname}}*
        build: {{build.number}}
        commit: {{build.branch}}:{{build.commit}}
        By: {{build.author}}
        {{build.message}}
        {{build.link}}

depends_on:
  - Build

trigger:
  status:
  - success
  - failure