kind: pipeline
type: docker
name: Build

steps:
  - name: install
    image: node:16
    volumes:
    - name: cache
      path: /drone/src/node_modules
    commands:
      - npm ci
    depends_on:
      - clone

  - name: tests
    image: node:16
    volumes:
    - name: cache
      path: /drone/src/node_modules
    commands:
      - npm test
    depends_on:
      - install

  - name: build
    image: node:16
    volumes:
      - name: cache
        path: /drone/src/node_modules
      - name: build
        path: /drone/src/build
    commands:
      - npm run build
      - ls
      - pwd
    depends_on:
      - tests

volumes:
  - name: cache
    host:
      path: /tmp/drone/node_modules
  - name: build
    host:
      path: /tmp/drone/build

---
kind: pipeline
type: docker
name: Publish

steps:
  - name: publish dev
    image: plugins/docker
    volumes:
      - name: build
        path: /drone/src/build
    settings:
      registry: rg.fr-par.scw.cloud/agence-public
      repo: rg.fr-par.scw.cloud/agence-public/create-react-app_test
      tags: [ latest ]
      username:
        from_secret: DOCKER_REGISTRY_USERNAME
      password:
        from_secret: DOCKER_REGISTRY_PASS
    depends_on:
      - clone

depends_on:
- Build

volumes:
  - name: build
    host:
      path: /tmp/drone/build

---
kind: pipeline
type: docker
name: Notify

clone:
  disable: true

steps:
  - name: send telegram
    image: appleboy/drone-telegram
    settings:
      token: 
        from_secret: TELEGRAM_BOT_TOKEN
      to: 
        from_secret: TELEGRAM_BOT_CANAL
      message: >
        {{#success build.status}}✅{{else}}❌{{/success}} Build {{build.status}}: *{{repo.fullname}}*
        build: {{build.number}}
        commit: {{build.branch}}:{{build.commit}}
        By: {{build.author}}
        {{build.message}}
        {{build.link}}

depends_on:
- Publish

trigger:
  status:
  - success
  - failure