kind: pipeline
type: docker
name: Build

steps:
  - name: restore cache
    image: drillster/drone-volume-cache
    settings:
      restore: true
      mount:
        - ./node_modules
    volumes:
      - name: cache
        path: /cache
    depends_on:
      - clone

  - name: install
    image: node:16
    commands:
      - npm ci
    depends_on:
      - restore cache

  - name: tests
    image: node:16
    commands:
      - npm test
    depends_on:
      - install

  - name: build
    image: node:16
    commands:
      - npm run build
    volumes:
      - name: cache
        path: /build
    depends_on:
      - tests

  - name: rebuild cache
    image: drillster/drone-volume-cache
    settings:
      rebuild: true
      mount:
        - ./node_modules
    volumes:
      - name: cache
        path: /cache
    depends_on:
      - build

volumes:
  - name: cache
    host:
      path: /tmp/drone/cache

---
kind: pipeline
type: docker
name: Publish

clone:
  disable: true

steps:
  - name: publish dev
    image: plugins/docker
    environment:
      NODE_ENV: development
    volumes:
      - name: cache
        path: /build
    settings:
      registry: rg.fr-par.scw.cloud/agence-public
      repo: rg.fr-par.scw.cloud/agence-public/create-react-app_test
      tags: [ latest ]
      cache_from: "rg.fr-par.scw.cloud/agence-public/create-react-app_test:latest"
      username:
        from_secret: DOCKER_REGISTRY_USERNAME
      password:
        from_secret: DOCKER_REGISTRY_PASS

  - name: publish prod
    image: plugins/docker
    environment:
      NODE_ENV: production
    volumes:
      - name: cache
        path: /build
    settings:
      registry: rg.fr-par.scw.cloud/agence-public
      repo: rg.fr-par.scw.cloud/agence-public/create-react-app_prod
      tags: [ latest ]
      cache_from: "rg.fr-par.scw.cloud/agence-public/create-react-app_prod:latest"
      username:
        from_secret: DOCKER_REGISTRY_USERNAME
      password:
        from_secret: DOCKER_REGISTRY_PASS

depends_on:
- Build

---
kind: pipeline
type: docker
name: Notify

steps:
  - name: send telegram
    image: appleboy/drone-telegram
    settings:
      token: 
        from_secret: TELEGRAM_BOT_TOKEN
      to: 
        from_secret: TELEGRAM_BOT_CANAL
      message: >
        {{#success build.status}}✅{{else}}❌{{/success}} Build {{build.status}}: *{{repo.fullname}}*
        build: {{build.number}}
        commit: {{build.branch}}:{{build.commit}}
        By: {{build.author}}
        {{build.message}}
        {{build.link}}

depends_on:
- Publish

trigger:
  status:
  - success
  - failure