kind: pipeline
type: docker
name: Pipeline-test-create-react-app

steps:
  - name: Installation et tests
    image: node:16
    commands:
      - npm ci
      - npm test

  - name: Build
    image: node:16
    commands:
      - npm build


  - name: docker  
    image: plugins/docker
    settings:
      registry: rg.fr-par.scw.cloud/images
      repo: foo/bar
      username:
        from_secret: docker_registry_username
      password:
        from_secret: docker_registry_key