query GetAllFieldsInCollection($collection: String!) {
    fields_in_collection(collection: $collection) {
        collection
        field
        type
        meta {
            interface
            options
            required
            readonly
            translations
        }
        schema {
            name
            foreign_key_table
            max_length
            default_value
        }
    }
}