name: Deploy Next to production

jobs:
  Deploy:
    runs-on: ubuntu-latest
    env:
      ARGOCD_URL: ${{ secrets.ARGOCD_URL }}
      ARGOCD_AUTH_TOKEN: ${{ secrets.ARGOCD_AUTH_TOKEN }}
    steps:
      - name: Getting argoCD
        run: |
          curl -sSL -o /usr/local/bin/argocd https://${ARGOCD_URL}/download/argocd-linux-amd64
          chmod +x /usr/local/bin/argocd
      - name: Getting argoCD
        run: |
          argocd app actions run ${{ github.event.repository.name }} restart --kind Deployment --resource-name production-next
