on:
  workflow_call:

jobs:
  Build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    container:
      image: node:16
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            **/node_modules
            ${{ steps.yarn-cache-dir-path.outputs.dir }}

          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Build code
        run: yarn run build