name: Deploy

on:
  pull_request:
    branches:
      - production
    types: [closed]

jobs:
  Deploy_To_Prod:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged && github.event.pull_request.base.ref == 'production'
    environment:
      name: production
      url: https://natiq.fr
    concurrency: production
    container:
      image: node:16
    steps:
      - name: Deploying code
        run: echo "Deploying to production"
