name: Deploy to production

on:
  pull_request:
    branches:
      - production
    types: [closed]

jobs:
  paths-filter:
    name: Paths filter
    runs-on: ubuntu-latest
    outputs:
      scripts: ${{ steps.filter.outputs.scripts }}
      next: ${{ steps.filter.outputs.next }}
      directus: ${{ steps.filter.outputs.directus }}
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            scripts:
              - 'directus/scripts/**'
            next:
              - "next/**"
              - "docker/prod/next/Dockerfile"
            directus:
              - "directus/npm-requirements.txt"
              - "directus/snapshot/**"
              - "docker/directus/prod/Dockerfile"

  Run_script:
    name: Run script
    runs-on: ubuntu-latest
    needs: paths-filter
    if: github.event.pull_request.merged && needs.paths-filter.outputs.scripts == 'true'
    steps:
      - uses: ./.github/workflows/deploy/prod/deploy_script

  Update_next:
    name: Update Next
    runs-on: ubuntu-latest
    needs: paths-filter
    if: github.event.pull_request.merged && needs.paths-filter.outputs.next == 'true'
    steps:
      - uses: ./.github/workflows/deploy/prod/deploy_next

  Update_directus:
    name: Update Directus
    runs-on: ubuntu-latest
    needs: paths-filter
    if: github.event.pull_request.merged && needs.paths-filter.outputs.directus == 'true'
    steps:
      - uses: ./.github/workflows/deploy/prod/deploy_directus
