name: Deploy

on:
  pull_request:
    branches:
      - staging
      - production
    types: [closed]

env:
  DOMAIN_URL_PRODUCTION: https://natiq.fr
  DOMAIN_URL_STAGING: https://staging.natiq.fr

jobs:
  Deploy_To_Staging:
    runs-on: ubuntu-latest
    environment:
      name: ${{ GITHUB_BASE_REF }}
      url: ${{ env.DOMAIN_URL_${{ GITHUB_BASE_REF }} }}
    concurrency: staging
    container:
      image: node:16
    steps:
      - name: Deploying code
        run: echo "Deploying to ${{ github.event.pull_request.base.ref }}"
