on:
  workflow_call:

jobs: 
  Install:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    container:
      image: node:16
    steps:
      - uses: actions/checkout@v3
      - name: Install packages
        run: yarn install --frozen-lockfile
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            **/node_modules
            ${{ steps.yarn-cache-dir-path.outputs.dir }}

          key: ${{ runner.os }}-yarn-${{ hashedFiles }}
          restore-keys: |
            ${{ runner.os }}-yarn-