name: Pull Request to ${{ GITHUB_BASE_REF }}

on:
  pull_request:
    branches:
      - production
      - staging

jobs:
  Push:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Pull ${{ GITHUB_REF_NAME }} image
        run: docker pull ${{ secrets.DOCKER_REGISTRY }}/${{ github.event.repository.name }}:${{ GITHUB_REF_NAME }}
      - name: Tag production image
        run: docker tag ${{ secrets.DOCKER_REGISTRY }}/${{ github.event.repository.name }}:${{ GITHUB_REF_NAME }} ${{ secrets.DOCKER_REGISTRY }}/${{ github.event.repository.name }}:${{ GITHUB_BASE_REF }}
      - name: Push production image
        run: docker push ${{ secrets.DOCKER_REGISTRY }}/${{ github.event.repository.name }}:${{ GITHUB_BASE_REF }}
# Update directus image if needed
