name: Pull Request to Staging

on:
  pull_request:
    branches:
      - staging

jobs:
  Push:
    runs-on: ubuntu-latest
    steps:
      - name: Retag to latest
        uses: tinact/docker.image-retag@master
        with:
          image_name: ${{ secrets.DOCKER_REGISTRY }}/${{ github.event.repository.name }}
          image_old_tag: dev
          image_new_tag: pre
          registry: ${{ secrets.DOCKER_REGISTRY }}
          registry_username: ${{ secrets.DOCKER_USERNAME }}
          registry_password: ${{ secrets.DOCKER_PASSWORD }}
  # Notify:
  #   runs-on: ubuntu-latest
  #   container:
  #     image: node:16
  #   steps:
  #     - name: send telegram message
  #       uses: appleboy/telegram-action@master
  #       with:
  #         to: ${{ secrets.TELEGRAM_TO }}
  #         token: ${{ secrets.TELEGRAM_TOKEN }}
  #         message: |
  #           ${{ github.actor }} created commit:
  #           Commit message: ${{ github.event.commits[0].message }}

  #           Repository: ${{ github.repository }}

  #           See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
