name: Pull Request to ${{ github.event.pull_request.base.ref }}

on:
  pull_request:
    branches:
      - production
      - staging

jobs:
  Push:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Pull ${{ github.event.pull_request.ref.name }} image
        run: docker pull ${{ secrets.DOCKER_REGISTRY }}/${{ github.event.repository.name }}:${{ github.event.pull_request.ref.name }}
      - name: Tag production image
        run: docker tag ${{ secrets.DOCKER_REGISTRY }}/${{ github.event.repository.name }}:${{ github.event.pull_request.ref.name }} ${{ secrets.DOCKER_REGISTRY }}/${{ github.event.repository.name }}:${{ github.event.pull_request.base.ref }}
      - name: Push production image
        run: docker push ${{ secrets.DOCKER_REGISTRY }}/${{ github.event.repository.name }}:${{ github.event.pull_request.base.ref }}
# Update directus image if needed
