name: Pull Request to Staging

on:
  pull_request:
    branches:
      - staging

jobs:
  Push:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Pull dev image
        run: docker pull ${{ secrets.DOCKER_REGISTRY }}/${{ github.event.repository.name }}:dev
      - name: Tag staging image
        run: docker tag ${{ secrets.DOCKER_REGISTRY }}/${{ github.event.repository.name }}:dev ${{ secrets.DOCKER_REGISTRY }}/${{ github.event.repository.name }}:staging
      - name: Push staging image
        run: docker push ${{ secrets.DOCKER_REGISTRY }}/${{ github.event.repository.name }}:staging
