name: Pull Request

on:
  pull_request:
    branches:    
      - develop
      - staging
      - production
      
jobs:
  Install:
    name: Install
    uses: shankiflang/drone-ci_test/.github/workflows/includes/install.yml@main  
  Build:
    name: Build
    needs: Install
    uses: shankiflang/drone-ci_test/.github/workflows/includes/build.yml@main
  # Notify