name: Pull Request

on:
  pull_request:
    branches:
      - develop
      - staging
      - production

jobs:
  Install:
    runs-on: ubuntu-latest
    container:
      image: node:16
    steps:
      - uses: actions/checkout@v3
      - name: Install packages
        run: yarn install --frozen-lockfile
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
  Build:
    runs-on: ubuntu-latest
    needs: Install
    container:
      image: node:16
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Build code
        run: yarn build
  Push:
    runs-on: ubuntu-latest
    needs: Build
    if: github.event.pull_request.base.ref == 'staging' || github.event.pull_request.base.ref == 'production'
    steps:
      - name: Push image to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: natiq/drone-ci_test:latest
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: rg.fr-par.scw.cloud/agence-public
          context: ./next
          dockerfile: ../docker/dev/next/Dockerfile
  # Notify:
  #   runs-on: ubuntu-latest
  #   container:
  #     image: node:16
  #   steps:
  #     - name: send telegram message
  #       uses: appleboy/telegram-action@master
  #       with:
  #         to: ${{ secrets.TELEGRAM_TO }}
  #         token: ${{ secrets.TELEGRAM_TOKEN }}
  #         message: |
  #           ${{ github.actor }} created commit:
  #           Commit message: ${{ github.event.commits[0].message }}

  #           Repository: ${{ github.repository }}

  #           See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
