name: Push

on:
  push:
    branches-ignore:    
      - develop
      - staging
      - production
      
jobs:
  Install:
    name: Install
    uses: shankiflang/drone-ci_test/.github/workflows/includes/install.yml@main  
  
  Tests:
    name: Tests
    needs: Install
    uses: shankiflang/drone-ci_test/.github/workflows/includes/tests.yml@main
  # Notify
