name: Push

on:
  push:
    branches-ignore:
      - develop
      - staging
      - production

jobs:
  Install:
    runs-on: ubuntu-latest
    container:
      image: node:16
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        id: yarn-cache
        with:
          path: |
            node_modules
          key: yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn
      - name: Install packages
        run: yarn --frozen-lockfile

  Test:
    runs-on: ubuntu-latest
    needs: Install
    container:
      image: node:16
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        id: yarn-cache
        with:
          path: |
            node_modules
          key: yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn
      - name: Test code
        run: yarn test
