name: Push

on:
  push:
    branches-ignore:
      - develop
      - staging
      - production

jobs:
  Install:
    runs-on: ubuntu-latest
    container:
      image: node:16
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        id: cache
        with:
          path: |
            node_modules
            build
          key: cache-${{ github.run_id }}
          restore-keys: |
            cache
      - name: Install packages
        run: yarn install --frozen-lockfile
  Test:
    runs-on: ubuntu-latest
    needs: Install
    container:
      image: node:16
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        id: cache
        with:
          path: |
            node_modules
            build
          key: cache-${{ github.run_id }}
          restore-keys: |
            cache
      - name: Test code
        run: yarn test
  # Notify:
  #   runs-on: ubuntu-latest
  #   container:
  #     image: node:16
  #   steps:
  #     - name: send telegram message
  #       uses: appleboy/telegram-action@master
  #       with:
  #         to: ${{ secrets.TELEGRAM_TO }}
  #         token: ${{ secrets.TELEGRAM_TOKEN }}
  #         message: |
  #           ${{ github.actor }} created commit:
  #           Commit message: ${{ github.event.commits[0].message }}

  #           Repository: ${{ github.repository }}

  #           See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
