name: Push

on:
  push:
    branches-ignore:    
      - develop
      - staging
      - production
      
jobs:
  Install:
    name: Install
    uses: shankiflang/drone-ci_test/.github/workflows/install.yml@main  
    with:
      steps.yarn-cache-dir-path.outputs.dir: steps.yarn-cache-dir-path.outputs.dir
      runner.os: runner.os
      hashedFiles: hashFiles('**/yarn.lock') 
  
  Tests:
    name: Tests
    needs: Install
    uses: shankiflang/drone-ci_test/.github/workflows/tests.yml@main
  # Notify
