name: Update Directus image production

on:
  pull_request:
    branches:
      - production
    paths:
      - "directus/npm-requirements.txt"
      - "directus/snapshot/**"
      - "docker/directus/prod/Dockerfile"

jobs:
  Push:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Pull staging image
        run: docker pull ${{ secrets.DOCKER_REGISTRY }}/directus:staging
      - name: Tag production image
        run: docker tag ${{ secrets.DOCKER_REGISTRY }}/directus:staging ${{ secrets.DOCKER_REGISTRY }}/directus:latest
      - name: Push production image
        run: docker push ${{ secrets.DOCKER_REGISTRY }}/directus:latest
