name: Update Directus image staging

on:
  pull_request:
    branches:
      - staging
    paths:
      - "directus/npm-requirements.txt"
      - "directus/snapshot/**"
      - "docker/directus/prod/Dockerfile"

jobs:
  Push:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Pull dev image
        run: docker pull ${{ secrets.DOCKER_REGISTRY }}/directus:dev
      - name: Tag staging image
        run: docker tag ${{ secrets.DOCKER_REGISTRY }}/directus:dev ${{ secrets.DOCKER_REGISTRY }}/directus:staging
      - name: Push staging image
        run: docker push ${{ secrets.DOCKER_REGISTRY }}/directus:staging
