name: Update Directus image staging

on:
  pull_request:
    branches:
      - staging
    paths:
      - "directus/npm-requirements.txt"
      - "directus/snapshot/**"
      - "docker/directus/prod/Dockerfile"

jobs:
  Push:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKER_REGISTRY }}/directus:staging
          context: directus
          file: docker/directus/prod/Dockerfile
