name: Update Next image production

on:
  pull_request:
    branches:
      - production
    paths:
      - "next/**"
      - "docker/prod/next/Dockerfile"

jobs:
  Push:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Pull staging image
        run: docker pull ${{ secrets.DOCKER_REGISTRY }}/${{ github.event.repository.name }}:staging
      - name: Tag production image
        run: docker tag ${{ secrets.DOCKER_REGISTRY }}/${{ github.event.repository.name }}:staging ${{ secrets.DOCKER_REGISTRY }}/${{ github.event.repository.name }}:latest
      - name: Push production image
        run: docker push ${{ secrets.DOCKER_REGISTRY }}/${{ github.event.repository.name }}:latest
